version: "3.8"

services:
  api:
    build: ./interview-drills-backend
    container_name: interview-drills-api
    ports:
      - "4000:4000"
    env_file:
      - .env

  web:
    build: ./interview-drills-frontend
    container_name: interview-drills-web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
